### ISSUE TITLE
artefact wil niet deploy'en op tomcat geen oplossing gevonden , ander project gebruikt om servlets te schrijven

### ISSUE THREAD

**Issue by kristofdewin** [kristofdewin/ServletTest_De_Win#1]
[2019-12-02 11:25:25,101] Artifact servletTest_De_Win:war: Error during artifact deployment. See server log for details.
		at java.xml/javax.xml.stream.util.StreamReaderDelegate.next(StreamReaderDelegate.java:84)
		at org.metatype.sxc.util.XoXMLStreamReaderImpl.next(XoXMLStreamReaderImpl.java:360)
[2019-12-02 11:25:25,101] Artifact servletTest_De_Win:war: org.apache.openejb.client.ClientRuntimeException: The exception sent could not be serialized or deserialized.  This is a mock recreation:
java.rmi.RemoteException: The bean encountered a non-application exception; nested exception is: 
	org.apache.openejb.OpenEJBRuntimeException: java.lang.IllegalStateException: Error starting child

**Comment by kristofdewin** [comment]
hoi Bart, ik ben hier zeer veel tijd aan kwijt geraakt, als de punten niet goed zijn wil ik deze test wel eens opnieuw maken, servlets getest met ander project en deze werken wel, tomcat issue heb ik niet opgelost gekregen

**Comment by kristofdewin** [comment]
fout in web xml gevonden , opgelost
